spring:
  application:
    name: datarize
  datasource:
    url: jdbc:mysql://localhost:3306/datarize
    username: user
    password: votmdnjem
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: update # create-drop
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace