insert into user (name) values ('A');
insert into user (name) values ('B');
insert into user (name) values ('C');
insert into user (name) values ('D');
insert into user (name) values ('E');
insert into user (name) values ('F');
insert into user (name) values ('G');
insert into user (name) values ('H');
insert into user (name) values ('I');
insert into user (name) values ('J');
insert into user (name) values ('AA');
insert into user (name) values ('BB');
insert into user (name) values ('CC');
insert into user (name) values ('DD');
insert into user (name) values ('EE');
insert into user (name) values ('FF');
insert into user (name) values ('GG');
insert into user (name) values ('HH');
insert into user (name) values ('II');
insert into user (name) values ('JJ');

insert into cabinet (cabinet_id, name, capacity) values (1, "A 회의실", 3);
insert into cabinet (cabinet_id, name, capacity) values (2, "B 회의실", 5);
insert into cabinet (cabinet_id, name, capacity) values (3, "C 회의실", 10);